### ISSUE TITLE
CSS background image fails to load because of backslash

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/file-loader#256]
node 9.5
file-loader ^1.1.9

With the following approach I have a problem with background images in css files.
The last slash is a backslash!

![image](https://user-images.githubusercontent.com/966368/36629516-ed9a86e2-1956-11e8-9bdf-09b7c456e069.png)

```
{ // SO
test: /\.(png|ico|svg|jpg|gif)$/,
exclude: /node_modules/,
use: {              
	loader: 'file-loader',
	options: {
	name: function (fullPath) {
		console.log(path.relative(__dirname + '/src', fullPath)); // --> images\blue.jpg                      
		return path.relative(__dirname + '/src', fullPath);
	}
	}
}
}
```

**Folder path `src\images\`**

**The `blue.jpg` is requested in my css file:**
 
```
.hello {
    background: url('../images/blue.jpg');
}
```

**Comment by michael-ciniawsky** [comment]
Use `path.posix.relative` to normalize the `path`, I also recommend to use `options.outputPath {Function}` and/or `options.useRelativePath` for this instead

**Comment by Legends** [comment]
The problem is I want to resemble the folder structure in `src `to `dist`, that's why i use the above approach.
With `options.outputPath {Function}` I only get the file name.

In `src `I have `images/icons`, with your approach I get `images `and `icons `in the root of `dist`.

I fixed the above issue by using a regex to replace the slashes.

**Comment by evilebottnawi** [comment]
@Legends Can you create minimum reproducible test repo?

**Comment by Legends** [comment]
Here it is: [repo](https://github.com/Legends/File-Loader-Issue)

**Comment by ldwonday** [comment]
I met the same problem!
This is my config: 
`...js
const relativeFileLoader = (ext = '[ext]') => ({
	loader: 'file-loader',
	options: {
		useRelativePath: true,
		name: `[name].${ext}`,
		context: resolve('src')
	}
});
`

**Comment by evilebottnawi** [comment]
@ldwonday why you use `useRelativePath` option?

**Comment by ldwonday** [comment]
@evilebottnawi I am so sorry, maybe this porblem is other package's bug, and it was fixed!

**Comment by Nickman87** [comment]
Same issue here.

The following config:
```
{
	test: /\.(svg|png|jpg|gif)$/,
	use: [{
		loader: "file-loader",
		options: {
			name: "[path][name].[ext]",
			outputPath: "images",
			context: "node_modules"
		}
	}]
}
```
provides me with paths like: `images\some\path\file.svg`

Changing this to the following:
```
{
	test: /\.(svg|png|jpg|gif)$/,
	use: [{
		loader: "file-loader",
		options: {
			name: "[path][name].[ext]",
			outputPath: function (fullPath) {
				return `images/${fullPath}`;
			},
			context: "node_modules"
		}
	}]
}
```
provides me with paths like: `images/some/path/file.svg` as expected.

The lines that cause this difference seem to be these:
```
  if (options.outputPath) {
    if (typeof options.outputPath === 'function') {
      outputPath = options.outputPath(url);
    } else {
      outputPath = path.posix.join(options.outputPath, url);
    }
  }
```
Maybe this issue is related to this one: https://github.com/nodejs/node/issues/13887 ?

**Comment by evilebottnawi** [comment]
@Nickman87 friendly ping. Problem still exists? If yes can you create minimum reproducible test repo?

**Comment by Nickman87** [comment]
I have not yet found the time to make a small test repo. I will try to get it done in the coming days!

**Comment by evilebottnawi** [comment]
@Nickman87 friendly ping

**Comment by Nickman87** [comment]
@evilebottnawi I'm sorry, I completely forgot.
I just made a basic setup, which corresponds to my other setup and it is working as expected, no issues 😮 

I'll have to cross reference more stuff to see what is going wrong to get a sample project that actually fails...
